api_platform:
    title: 'Task Manager API'
    description: 'API for managing tasks and users'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        stateless: true
        security: 'is_granted("ROLE_USER")'
